name: CD

on:
  push:
    branches:
      - main
      - feature/login

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gerar-artefato:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Gerar aplicacao para producao
        run: npm run build

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao-react
          path: dist
          retention-days: 7