name: CI

on:
  push:
    branches:
      - main
      - feature/login

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verificar-aplicacao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar o codigo
        run: npm run lint

      - name: Gerar build de producao
        run: npm run build